--------------------------------------------------------
--  DDL for Table DASH_PARAM
--------------------------------------------------------

  CREATE TABLE "CS5226"."DASH_PARAM" 
   (	"PARAM" VARCHAR2(255 BYTE), 
	"GREEN_S" NUMBER, 
	"GREEN_E" NUMBER, 
	"YELLOW_S" NUMBER, 
	"YELLOW_E" NUMBER, 
	"RED_S" NUMBER, 
	"RED_E" NUMBER, 
	"DESC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DASH_SQL
--------------------------------------------------------

  CREATE TABLE "CS5226"."DASH_SQL" 
   (	"PARAM" VARCHAR2(20 BYTE), 
	"SQL" VARCHAR2(4000 BYTE), 
	"ADVICE" VARCHAR2(255 BYTE), 
	"DESC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DASH_CONFIG
--------------------------------------------------------

  CREATE TABLE "SYS"."DASH_CONFIG" 
   (	"K" VARCHAR2(255 BYTE), 
	"KVAL" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 --------------------------------------------------------
--  DDL for Table DASH_PARAM_V
--------------------------------------------------------

  CREATE TABLE "SYS"."DASH_PARAM_V" 
   (	"PARAM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VAL" NUMBER, 
	"SNAP_DT" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
